name:                hif
version:             0.1.0.0
github:              "harryaskham/hif"
license:             BSD3
author:              "Harry Askham"
maintainer:          "harry@askham.ai"
copyright:           "2020 Harry Askham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hif#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- mtl
- random
- MonadRandom
- listsafe

library:
  source-dirs: src

executables:
  hif-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hif

tests:
  hif-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hif
