name:                hif
version:             0.1.0.0
github:              "harryaskham/hif"
license:             BSD3
author:              "Harry Askham"
maintainer:          "harryaskham@gmail.com"
copyright:           "2021 Harry Askham"

extra-source-files:
- README.org

description:         Please see the README on GitHub at <https://github.com/harryaskham/hif#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- mtl
- random
- MonadRandom
- listsafe
- data-default
- unliftio
- unliftio-core
- containers
- transformers
- text
- text-show
- parsec
- extra
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  hif-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hif

tests:
  hif-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hif
